# Admin app (authenticated via mTLS, CN=admin)
user admin
topic readwrite ArduinoGatekeeper/Admin/UserList
topic read ArduinoGatekeeper/+/Status
topic read ArduinoGatekeeper/+/Log

# Clients
pattern write ArduinoGatekeeper/%u/Log
pattern write ArduinoGatekeeper/%u/Status
pattern read  ArduinoGatekeeper/Admin/UserList