# Access control
acl_file /mosquitto/config/acl.conf

# Arduino clients — TLS + username/password
listener 8883
protocol mqtt
cafile   /mosquitto/certs/root/ca.crt
certfile /mosquitto/certs/server/server.crt
keyfile  /mosquitto/certs/server/server.key
password_file /mosquitto/config/passwd.conf
require_certificate false
allow_anonymous false

# Admin app — mTLS (client cert required)
listener 8884
protocol mqtt
cafile   /mosquitto/certs/root/ca.crt
certfile /mosquitto/certs/server/server.crt
keyfile  /mosquitto/certs/server/server.key
require_certificate true
use_identity_as_username true
allow_anonymous false

# Log system configuration
log_type all 
log_dest stdout