# Backend
user AGK_Backend
topic write AGK/users/add
topic write AGK/users/remove
topic read  AGK/+/dev_status
topic read  AGK/+/scan

# Clients
pattern write AGK/%u/scan
pattern write AGK/%u/dev_status
pattern read  AGK/users/add
pattern read  AGK/users/remove