# Backend
user agk_backend
topic write AGK/+/add_users
topic write AGK/+/remove_users
topic read  AGK/+/dev_status
topic read  AGK/+/scan

# Clients
pattern write AGK/%u/scan
pattern write AGK/%u/dev_status
pattern read  AGK/%u/add_users
pattern read  AGK/%u/remove_users