# Backend
user agk_backend
topic write AGK/+/add_user
topic write AGK/+/remove_user
topic read  AGK/+/dev_status
topic read  AGK/+/scan

# Clients
pattern write AGK/%u/scan
pattern write AGK/%u/dev_status
pattern read  AGK/%u/add_user
pattern read  AGK/%u/remove_user